services:
  - type: web
    name: gemini-journal
    env: node
    region: singapore # or oregon, ohio, frankfurt
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: ENFORCE_APP_CHECK
        value: "false"
